### ISSUE TITLE
path may not be null or empty string. path='null' Open File

### ISSUE THREAD

**Issue by Claude12** [citiususc/calendula#107] opened 2018-04-04 14:18 UTC
getting this error when i try to build the project.

**Comment by ontherunvaro** [comment] 2018-04-04 14:51
Hello, we need a bit more info:

* Is this when building with `gradle` or when building with Android Studio? If it's `gradle`, please post the whole command you are using. If it's Android Studio, please post which build variant you have selected.

* Is this a duplicate of issue #99? In any case I assume we can close that one, can't we?

**Comment by ontherunvaro** [comment] 2018-04-04 15:29
Your problem is that you don't  have a valid signing config in `keystore.properties`. For obvious reasons we don't upload our keystore to Github. 

You can either:

1. Use a variant that doesn't sign the builds. I recommend `developDebug` as instructed in our README. You can choose it from the `Build Variants` dialog in Android Studio.
2. Generate your own keystore and use that for building

**Comment by Claude12** [comment] 2018-04-05 15:48
okay noted. thank you.

**Closed** 2018-04-05 15:48 UTC
Labels: question

**Comment by vivimendoza16** [comment] 2018-04-25 07:13
Hello, I need to build the project by command line, I am following the instruction of repository but when I execute the command I always get this error in console 

> File to path may not be null or empty string. path='null'

**Comment by ontherunvaro** [comment] 2018-04-25 08:54
@vivimendoza16 create your own `keystore.properties` file with dummy values. You can see the keys needed in `build.gradle`: https://github.com/citiususc/calendula/blob/master/Calendula/build.gradle#L93.

For example, you could create `keystore.properties` with these contents:

```
keyAlias=foo
keyPassword=foo
storeFile=foo
storePassword=foo
```

**Comment by astalavistababeee** [comment] 2018-07-28 09:53
Keystore file 'C:\Users\rajab\AndroidStudioProjects\calendula\Calendula\foo' not found for signing config 'release'.
what should i do ?

**Comment by astalavistababeee** [comment] 2018-07-28 09:55
@ontherunvaro    when i create keystore files as u said following error occured Keystore file 'C:\Users\rajab\AndroidStudioProjects\calendula\Calendula\foo' not found for signing config 'release'.

how to clear this?

**Comment by ontherunvaro** [comment] 2018-07-29 20:55
@astalavistababeee please follow the instructions outlined above: create the dummy `keystore.properties` and use the `developDebug` flavor to build. That should clear all your errores.
